# Internal build -> https://macro.int.pgmac.net/incidents/
#
# Everything except the target-specific settings below lives in mkdocs-base.yml.

INHERIT: mkdocs-base.yml

site_url: https://macro.int.pgmac.net/incidents/
